services:
  - type: web
    name: revomate-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: GROQ_API_KEY
        sync: false
      - key: MODEL_NAME
        value: llama-3.1-8b-instant
      - key: VECTOR_DB_PATH
        value: /data/chroma_db
      - key: DATA_PATH
        value: ./data/revomate_rag_expanded.txt
    disk:
      name: chroma-data
      mountPath: /data
      sizeGB: 1
